import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { asNum, asVec3, Field, type Vec3 } from "./core";
import { makeFieldCtx } from "./evaluator";
import { Geometry, Mesh } from "./geometry";
import {
  adaptiveSurfaceNetsForTest,
  boundedGridLayoutForTest,
  boundedVolumeResolutionForTest,
  MAX_DENSE_SDF_SAMPLES,
  meshToSdfGridForTest,
  pointsToSdfGridForTest,
  resampleVolumeGridForTest,
  setDenseSdfSampleBudget,
  surfaceNetsForTest,
} from "./nodes/volume";
import { OPENVDB_AMBIGUOUS_FACE, OPENVDB_EDGE_GROUPS, openVdbGroupCount } from "./openvdb-edge-groups";
import { APPROXIMATIONS, REGISTRY, type EvalAPI, type SockVal, type VolumeGrid } from "./registry";

type SdfFixtureCount = { vertices: number; edges: number; faces: number };
type UvSdfBlenderFixture = {
  blender: string;
  generator: string;
  non_manifold_sdf: Record<string, SdfFixtureCount>;
  adaptive_cube_sdf: Record<string, SdfFixtureCount>;
  "budget_cube_10_voxel_0.1": {
    requested_samples: number;
    vertices: number;
    edges: number;
    faces: number;
  };
};

const blenderFixture = JSON.parse(readFileSync(
  new URL("../../tools/fixtures/uv-sdf-blender-5.1.2-summary.json", import.meta.url),
  "utf8",
)) as UvSdfBlenderFixture;

function cubeGeometry(): Geometry {
  const geometry = new Geometry();
  const mesh = new Mesh();
  mesh.positions = [
    [0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0],
    [0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1],
  ];
  mesh.faces = [
    [0, 3, 2, 1], [4, 5, 6, 7],
    [0, 1, 5, 4], [1, 2, 6, 5],
    [2, 3, 7, 6], [3, 0, 4, 7],
  ];
  geometry.mesh = mesh;
  return geometry;
}

function apiWith(values: Record<string, SockVal>): EvalAPI {
  const input = (name: string) => values[name];
  const field = (name: string) => {
    const value = input(name);
    return value instanceof Field ? value : Field.of(typeof value === "number" ? value : 0);
  };
  return {
    node: { name: "volume-test", type: "volume-test", label: null, inputs: [], outputs: [] },
    input,
    inputs: (name) => values[name] === undefined ? [] : [values[name]],
    geoInputs: (name) => values[name] instanceof Geometry ? [values[name] as Geometry] : [],
    geo: (name) => values[name] instanceof Geometry ? values[name] as Geometry : new Geometry(),
    field,
    num: (name) => {
      const value = input(name);
      return value instanceof Field ? asNum(value.value) : typeof value === "number" ? value : 0;
    },
    vec: (name) => {
      const value = input(name);
      return value instanceof Field ? asVec3(value.value) : [0, 0, 0];
    },
    bool: (name) => Boolean(asNum(field(name).value)),
    str: (name) => String(input(name) ?? ""),
    ref: () => null,
    prop: (_name, fallback) => fallback as never,
    resolve: (value, geometry, domain) => value.array(makeFieldCtx(geometry, domain)),
  };
}

function gridValueAt(
  grid: ReturnType<typeof meshToSdfGridForTest>,
  point: Vec3,
): number {
  const coordinate = point.map((value, axis) =>
    Math.round((value - grid.origin[axis]) / grid.voxelSize[axis])) as Vec3;
  return grid.values[
    coordinate[2] * grid.resolution[0] * grid.resolution[1]
      + coordinate[1] * grid.resolution[0]
      + coordinate[0]
  ];
}

test("bundles the complete OpenVDB ambiguous-cell topology tables", () => {
  assert.equal(OPENVDB_AMBIGUOUS_FACE.length, 256);
  assert.equal(OPENVDB_EDGE_GROUPS.length, 256 * 13);
  assert.equal(OPENVDB_AMBIGUOUS_FACE[52], 2);
  assert.equal(openVdbGroupCount(52), 1);
  assert.equal(openVdbGroupCount(255 - 52), 2);
});

test("loads the checked Blender UV/SDF oracle generated by the parity probe", () => {
  assert.equal(blenderFixture.blender, "5.1.2");
  assert.equal(blenderFixture.generator, "tools/uv_sdf_blender_probe.py");
  assert.deepEqual(blenderFixture.adaptive_cube_sdf["0"], {
    vertices: 152,
    edges: 300,
    faces: 150,
  });
  assert.deepEqual(blenderFixture.adaptive_cube_sdf["1"], {
    vertices: 8,
    edges: 12,
    faces: 6,
  });
});

test("surface nets closes a crossing on each axis' negative boundary", () => {
  const resolution: Vec3 = [4, 4, 4];
  const index = (x: number, y: number, z: number) => z * resolution[0] * resolution[1] + y * resolution[0] + x;

  for (let axis = 0; axis < 3; axis++) {
    const values = new Float32Array(4 * 4 * 4).fill(1);
    const coordinate: Vec3 = [1, 1, 1];
    coordinate[axis] = 0;
    values[index(...coordinate)] = -1;

    const mesh = surfaceNetsForTest(values, resolution, 0, [0, 0, 0], [1, 1, 1]);
    assert.equal(mesh.positions.length, 4, `axis ${axis} should create four incident cell vertices`);
    assert.equal(mesh.faces.length, 1, `axis ${axis} should emit the negative-boundary cap`);
    assert.equal(mesh.faces[0].length, 4);
  }
});

test("surface nets preserves Blender's directional quad winding and diagonals", () => {
  const resolution: Vec3 = [4, 4, 4];
  const index = (x: number, y: number, z: number) => z * resolution[0] * resolution[1] + y * resolution[0] + x;
  const expectedForward = [
    [1, 0, 2, 3],
    [2, 0, 1, 3],
    [0, 2, 3, 1],
  ];
  const expectedReverse = [
    [3, 2, 0, 1],
    [3, 1, 0, 2],
    [2, 0, 1, 3],
  ];

  for (const inside of [true, false]) for (let axis = 0; axis < 3; axis++) {
    const values = new Float32Array(4 * 4 * 4).fill(inside ? 1 : -1);
    const coordinate: Vec3 = [1, 1, 1];
    coordinate[axis] = 0;
    values[index(...coordinate)] = inside ? -1 : 1;

    const mesh = surfaceNetsForTest(values, resolution, 0, [0, 0, 0], [1, 1, 1]);
    assert.equal(mesh.faces.length, 1, `axis ${axis}, inside=${inside}`);
    assert.deepEqual(mesh.faces[0], (inside ? expectedForward : expectedReverse)[axis]);
  }
});

test("volume resampling uses OpenVDB's sparse lower guard and ceil-rounded extent", () => {
  const volume = {
    kind: "GNVM_VOLUME_GRID" as const,
    background: 0,
    min: [0, 0, 0] as Vec3,
    max: [2, 2, 2] as Vec3,
    resolution: [3, 3, 3] as Vec3,
    origin: [0, 0, 0] as Vec3,
    voxelSize: [1, 1, 1] as Vec3,
    values: new Float32Array(27).fill(1),
  };
  const resampled = resampleVolumeGridForTest(volume, 0.6);
  assert.deepEqual(resampled.resolution, [10, 10, 10]);
  assert.deepEqual(resampled.origin.map((value) => Number(value.toFixed(6))), [-1.2, -1.2, -1.2]);
  const index = (x: number, y: number, z: number) =>
    z * resampled.resolution[0] * resampled.resolution[1] + y * resampled.resolution[0] + x;
  assert.equal(resampled.values[index(0, 2, 2)], 0, "outer lower plane must be hard background");
  assert.ok(resampled.values[index(1, 2, 2)] > 0, "one lower BoxSampler support layer must remain interpolated");
  assert.equal(resampled.values[index(9, 2, 2)], 0, "ceil-rounded upper guard must reach background");

  const mesh = surfaceNetsForTest(resampled.values, resampled.resolution, 0.5, resampled.origin, resampled.spacing);
  assert.equal(mesh.positions.length, 146);
  assert.equal(mesh.faces.length, 144);
  const edgeUses = new Map<string, number>();
  for (const face of mesh.faces) for (let corner = 0; corner < face.length; corner++) {
    const a = face[corner], b = face[(corner + 1) % face.length];
    const key = a < b ? `${a},${b}` : `${b},${a}`;
    edgeUses.set(key, (edgeUses.get(key) ?? 0) + 1);
  }
  assert.ok([...edgeUses.values()].every((uses) => uses === 2), "boundary-touching surface must close manifoldly");
});

test("volume resampling preserves the numeric background of inactive OpenVDB regions", () => {
  const volume = {
    kind: "GNVM_VOLUME_GRID" as const,
    background: 1,
    min: [0, 0, 0] as Vec3,
    max: [7, 7, 7] as Vec3,
    resolution: [8, 8, 8] as Vec3,
    origin: [0, 0, 0] as Vec3,
    voxelSize: [1, 1, 1] as Vec3,
    values: new Float32Array(8 * 8 * 8).fill(1),
  };
  const resampled = resampleVolumeGridForTest(volume, 0.75);
  assert.ok(
    resampled.values.every((value) => value === 1),
    "GridTransformer keeps the source tree's numeric background even when every voxel is inactive",
  );
});

test("Mesh to SDF Grid stores signed narrow-band distances for a closed mesh", () => {
  const cube = cubeGeometry();
  const grid = meshToSdfGridForTest(cube.mesh!, 0.25, 3);

  assert.deepEqual(grid.resolution, [11, 11, 11]);
  assert.deepEqual(grid.origin, [-0.75, -0.75, -0.75]);
  assert.equal(grid.background, 0.75);
  assert.ok(gridValueAt(grid, [0.5, 0.5, 0.5]) < 0, "cube center must have a negative SDF");
  assert.equal(gridValueAt(grid, [-0.75, -0.75, -0.75]), 0.75, "far exterior clamps to the band");
  assert.equal(
    gridValueAt(grid, [0, 0.5, 0.5]),
    -1.1920928955078125e-7,
    "surface samples retain OpenVDB's inside-biased float32 boundary",
  );

  // Blender 5.1.2 produces the same 5x5 quad layout on every cube side for
  // Mesh to SDF Grid -> Grid to Mesh at this spacing.
  const mesh = surfaceNetsForTest(
    grid.values,
    grid.resolution,
    0,
    grid.origin,
    grid.voxelSize,
  );
  assert.equal(mesh.positions.length, blenderFixture.adaptive_cube_sdf["0"].vertices);
  assert.equal(mesh.faces.length, blenderFixture.adaptive_cube_sdf["0"].faces);
  const levels = [0, 1, 2].map((axis) =>
    [...new Set(mesh.positions.map((point) =>
      Math.round(point[axis] * 1e7) / 1e7))].sort((a, b) => a - b));
  assert.deepEqual(levels, [
    [-1e-7, 0, .125, .375, .625, .875, 1, 1.0000001],
    [-1e-7, 0, .125, .375, .625, .875, 1, 1.0000001],
    [-1e-7, 0, .125, .375, .625, .875, 1, 1.0000001],
  ]);
});

test("Mesh to SDF Grid matches Blender's open and non-manifold polygon-soup fixtures", () => {
  const evaluate = (positions: Vec3[], faces: number[][]) => {
    const mesh = new Mesh();
    mesh.positions = positions;
    mesh.faces = faces;
    const grid = meshToSdfGridForTest(mesh, .25, 3);
    return surfaceNetsForTest(grid.values, grid.resolution, 0, grid.origin, grid.voxelSize);
  };
  const open = evaluate(
    [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]],
    [[0, 1, 2, 3]],
  );
  assert.equal(open.positions.length, blenderFixture.non_manifold_sdf.open_quad.vertices);
  assert.equal(open.faces.length, blenderFixture.non_manifold_sdf.open_quad.faces);

  const threeFaceEdge = evaluate(
    [[0, 0, 0], [1, 0, 0], [.5, 1, 0], [.5, 0, 1], [.5, -1, 0]],
    [[0, 1, 2], [1, 0, 3], [0, 1, 4]],
  );
  assert.equal(threeFaceEdge.positions.length, blenderFixture.non_manifold_sdf.three_face_edge.vertices);
  assert.equal(threeFaceEdge.faces.length, blenderFixture.non_manifold_sdf.three_face_edge.faces);

  const flipped = cubeGeometry().mesh!;
  flipped.faces[0] = [...flipped.faces[0]].reverse();
  const flippedGrid = meshToSdfGridForTest(flipped, .25, 3);
  const flippedOutput = surfaceNetsForTest(
    flippedGrid.values,
    flippedGrid.resolution,
    0,
    flippedGrid.origin,
    flippedGrid.voxelSize,
  );
  assert.equal(
    flippedOutput.positions.length,
    blenderFixture.non_manifold_sdf.cube_one_flipped_face.vertices,
  );
  assert.equal(
    flippedOutput.faces.length,
    blenderFixture.non_manifold_sdf.cube_one_flipped_face.faces,
  );
});

test("Grid to Mesh adaptivity is functional, monotonic, and reaches the canonical coarse cube", () => {
  const grid = meshToSdfGridForTest(cubeGeometry().mesh!, .25, 3);
  const outputs = [0, .1, .5, 1].map((adaptivity) =>
    adaptiveSurfaceNetsForTest(
      grid.values,
      grid.resolution,
      0,
      grid.origin,
      grid.voxelSize,
      adaptivity,
    ));
  assert.deepEqual(outputs.map((mesh) => mesh.positions.length), [152, 98, 26, 8]);
  assert.deepEqual(outputs.map((mesh) => mesh.faces.length), [150, 96, 24, 6]);
  assert.equal(outputs[0].positions.length, blenderFixture.adaptive_cube_sdf["0"].vertices);
  assert.equal(outputs[0].faces.length, blenderFixture.adaptive_cube_sdf["0"].faces);
  assert.equal(outputs.at(-1)?.positions.length, blenderFixture.adaptive_cube_sdf["1"].vertices);
  assert.equal(outputs.at(-1)?.faces.length, blenderFixture.adaptive_cube_sdf["1"].faces);
  for (let index = 1; index < outputs.length; index++) {
    assert.ok(outputs[index].positions.length < outputs[index - 1].positions.length);
    assert.ok(outputs[index].faces.length < outputs[index - 1].faces.length);
  }
  // Blender 5.1.2's OpenVDB oracle also reaches 8 vertices / 6 faces at 1.0;
  // intermediate topology remains explicitly bounded rather than exact.
});

test("dense SDF budget resampling exposes requested and effective lattice contracts", () => {
  const layout = boundedGridLayoutForTest([0, 0, 0], [10, 10, 10], .1, 3);
  assert.equal(layout.requestedVoxelSize, .1);
  assert.equal(
    layout.requestedSampleCount,
    blenderFixture["budget_cube_10_voxel_0.1"].requested_samples,
  );
  assert.equal(layout.budgetAdjusted, true);
  assert.equal(layout.sampleBudget, MAX_DENSE_SDF_SAMPLES);
  assert.ok(layout.resolution[0] * layout.resolution[1] * layout.resolution[2]
    <= MAX_DENSE_SDF_SAMPLES);
  assert.ok(layout.voxelSize[0] > layout.requestedVoxelSize);

  setDenseSdfSampleBudget(2_000_000);
  try {
    const manualPreview = boundedGridLayoutForTest([0, 0, 0], [10, 10, 10], .1, 3);
    assert.equal(manualPreview.budgetAdjusted, false);
    assert.equal(manualPreview.requestedSampleCount, 107 ** 3);
    assert.equal(manualPreview.resolution[0] ** 3, 107 ** 3);
  } finally {
    setDenseSdfSampleBudget(null);
  }
});

test("dense SDF budget rejects values that would silently disable the allocation cap", () => {
  for (const invalid of [Number.NaN, Infinity, -Infinity, 0, -1])
    assert.throws(
      () => setDenseSdfSampleBudget(invalid),
      /finite positive number/,
    );

  const layout = boundedGridLayoutForTest([0, 0, 0], [10, 10, 10], .1, 3);
  assert.equal(layout.sampleBudget, MAX_DENSE_SDF_SAMPLES);
  assert.equal(layout.budgetAdjusted, true);
});

test("Volume Cube deterministically coarsens oversized authored resolutions", () => {
  const volumeCube = REGISTRY.get("GeometryNodeVolumeCube");
  assert.ok(volumeCube);
  assert.deepEqual(boundedVolumeResolutionForTest([100, 100, 100], 64), {
    resolution: [4, 4, 4],
    requestedSampleCount: 1_000_000,
    budgetAdjusted: true,
    sampleBudget: 64,
  });

  const previousCount = APPROXIMATIONS.get("GeometryNodeVolumeCube") ?? 0;
  setDenseSdfSampleBudget(64);
  try {
    const value = volumeCube(apiWith({
      Min: Field.of([0, 0, 0]),
      Max: Field.of([1, 2, 3]),
      "Resolution X": Field.of(100),
      "Resolution Y": Field.of(100),
      "Resolution Z": Field.of(100),
      Background: Field.of(0),
      Density: Field.of(1),
    })).Volume;
    assert.ok(value && typeof value === "object" && value.kind === "GNVM_VOLUME_GRID");
    const volume: VolumeGrid = value;
    assert.deepEqual(volume.resolution, [4, 4, 4]);
    assert.equal(volume.values.length, 64);
    assert.equal(volume.requestedSampleCount, 1_000_000);
    assert.equal(volume.sampleBudget, 64);
    assert.equal(volume.budgetAdjusted, true);
    assert.deepEqual(volume.voxelSize, [1 / 3, 2 / 3, 1]);
    assert.ok(volume.values.every((sample) => sample === 1));
  } finally {
    setDenseSdfSampleBudget(null);
  }
  assert.equal(APPROXIMATIONS.get("GeometryNodeVolumeCube"), previousCount + 1);
});

test("Volume to Mesh resampling coarsens a tiny voxel request before allocating", () => {
  const volumeToMesh = REGISTRY.get("GeometryNodeVolumeToMesh");
  assert.ok(volumeToMesh);
  const volume: VolumeGrid = {
    kind: "GNVM_VOLUME_GRID",
    background: 0,
    min: [0, 0, 0],
    max: [7, 7, 7],
    resolution: [8, 8, 8],
    origin: [0, 0, 0],
    voxelSize: [1, 1, 1],
    values: new Float32Array(8 ** 3).fill(1),
    requestedVoxelSize: 1,
    requestedSampleCount: 8 ** 3,
    budgetAdjusted: false,
    sampleBudget: MAX_DENSE_SDF_SAMPLES,
  };

  const previousCount = APPROXIMATIONS.get("GeometryNodeVolumeToMesh") ?? 0;
  setDenseSdfSampleBudget(1_000);
  try {
    const resampled = resampleVolumeGridForTest(volume, 1e-6);
    assert.equal(resampled.requestedSpacing, 1e-6);
    assert.ok(resampled.requestedSampleCount > 1_000);
    assert.ok(resampled.values.length <= 1_000);
    assert.equal(resampled.sampleBudget, 1_000);
    assert.equal(resampled.budgetAdjusted, true);
    assert.ok(Math.max(...resampled.spacing) > resampled.requestedSpacing);

    const output = volumeToMesh(apiWith({
      Volume: volume,
      "Resolution Mode": "SIZE",
      "Voxel Size": Field.of(1e-6),
      Threshold: Field.of(0.5),
    })).Mesh;
    assert.ok(output instanceof Geometry);
  } finally {
    setDenseSdfSampleBudget(null);
  }
  assert.equal(APPROXIMATIONS.get("GeometryNodeVolumeToMesh"), previousCount + 1);
});

test("Points to SDF Grid unions variable-radius spheres and extracts a closed surface", () => {
  const grid = pointsToSdfGridForTest(
    [[0, 0, 0], [1.5, 0, 0]],
    [1, 0.5],
    0.25,
  );
  assert.ok(gridValueAt(grid, [0, 0, 0]) < 0);
  assert.ok(gridValueAt(grid, [1.5, 0, 0]) < 0);
  assert.ok(gridValueAt(grid, [0.5, 0, 0]) < 0, "overlapping sphere union stays inside");

  const mesh = surfaceNetsForTest(grid.values, grid.resolution, 0, grid.origin, grid.voxelSize);
  assert.ok(mesh.positions.length > 100);
  assert.ok(mesh.faces.length > 100);
  const edgeUses = new Map<string, number>();
  for (const face of mesh.faces) for (let corner = 0; corner < face.length; corner++) {
    const a = face[corner], b = face[(corner + 1) % face.length];
    const key = a < b ? `${a},${b}` : `${b},${a}`;
    edgeUses.set(key, (edgeUses.get(key) ?? 0) + 1);
  }
  assert.ok([...edgeUses.values()].every((uses) => uses === 2));
});

test("SDF node handlers compose through the volume-grid socket and report bounded execution", () => {
  const meshToGrid = REGISTRY.get("GeometryNodeMeshToSDFGrid");
  const gridToMesh = REGISTRY.get("GeometryNodeGridToMesh");
  const pointsToGrid = REGISTRY.get("GeometryNodePointsToSDFGrid");
  assert.ok(meshToGrid && gridToMesh && pointsToGrid);

  const previousMeshCount = APPROXIMATIONS.get("GeometryNodeMeshToSDFGrid") ?? 0;
  const previousGridCount = APPROXIMATIONS.get("GeometryNodeGridToMesh") ?? 0;
  const sdf = meshToGrid(apiWith({
    Mesh: cubeGeometry(),
    "Voxel Size": Field.of(0.25),
    "Band Width": Field.of(3),
  }))["SDF Grid"];
  const result = gridToMesh(apiWith({
    Grid: sdf,
    Threshold: Field.of(0),
    Adaptivity: Field.of(0),
  })).Mesh;

  assert.ok(result instanceof Geometry);
  assert.ok(result.mesh && result.mesh.positions.length > 0 && result.mesh.faces.length > 0);
  assert.equal(APPROXIMATIONS.get("GeometryNodeMeshToSDFGrid"), previousMeshCount + 1);
  assert.equal(APPROXIMATIONS.get("GeometryNodeGridToMesh"), previousGridCount + 1);
});
